# Generated by Django 3.1.2 on 2020-11-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='food_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
